name: user_repository
description: A repository that handles user related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  user_api:
    path: ../../api/user_api
  user_local_storage:
    path: ../../local_storage/user_local_storage
  user_sync_service:
    path: ../../sync/user_sync_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
