name: user_sync_service
description: A dart implementation of a synchronization service in extension to the general core_sync_service.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  core_sync_service:
    path: ../core_sync_service
  user_api:
    path: ../../api/user_api

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
