name: holz_logistik
description: A logistics app for wood industry.

publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.5
  flutter_map: ^5.0.0
  photo_view: ^0.15.0

  # Data Management
  provider: ^6.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.1

  # Network/API
  http: ^1.1.0
  connectivity_plus: ^6.1.3
  dio: ^5.3.2  # Alternative to http with more features

  # Location Services
  geolocator: ^13.0.2
  latlong2: ^0.9.0

  # Utilities
  image_picker: ^1.0.4
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - .env