name: holz_logistik
description: A logistics app for wood trading
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  core_database_service:
    path: packages/core/core_database_service
  core_sync_service:
    path: packages/core/core_sync_service
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  user_api:
    path: packages/user/user_api
  user_database_service:
    path: packages/user/user_database_service
  user_repository:
    path: packages/user/user_repository
  user_sync_service:
    path: packages/user/user_sync_service

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^1.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
