name: holz_logistik
description: A logistics app for wood trading
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  users_api:
    path: packages/users/users_api
  users_local_storage:
    path: packages/users/users_local_storage
  users_repository:
    path: packages/users/users_repository

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^1.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
