name: holz_logistik
description: A logistics application for wood management.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  path: ^1.8.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^0.8.7+5
  photo_view: ^0.14.0
  path_provider: ^2.0.15
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true