name: users_repository
description: A repository that handles user related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  users_api:
    path: ../users_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
