name: user_local_storage
description: A flutter implementation of the user UserLocalStorage that uses CoreLocalStorage and sqflite.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  core_local_storage:
    path: ../core_local_storage
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  sqflite: ^2.4.2
  user_api:
    path: ../../api/user_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
