name: authentication_repository
description: A dart implementation of the repository for authentication
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  authentication_api:
    path: ../../api/authentication_api
  authentication_sync_service:
    path: ../../sync/authentication_sync_service
  user_api:
    path: ../../api/user_api

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
