name: user_database_service
description: A flutter implementation of the user UserDatabaseService that uses CoreDatabaseService and sqflite.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  core_database_service:
    path: ../../core/core_database_service
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  sqflite: ^2.4.2
  user_api:
    path: ../user_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
