name: authentication_sync_service
description: A dart implementation of the authentication sync service
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  core_sync_service:
    path: ../core_sync_service

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
